name: Build
on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        required: true
        default: false

  pull_request_target:
    branches:
      - master
      - alpha

jobs:
  build:
    uses: qlik-oss/sn-gh-workflows/.github/workflows/build.yaml@v1
    secrets: inherit
    with:
      release: ${{ inputs.release || false}}
      release_branches: |
        [
          'master',
          {
            name: 'alpha',
            prerelease: true
          }
        ]
      api_specification_path: api-spec/spec.json
